### ISSUE TITLE
Перевод координат

### ISSUE THREAD

**Issue by denyszamiatin** [denyszamiatin/sea_battle#2]
Написать функцию, которая переводит игровые координаты, заданные как в #1 в координаты игрового поля - от 0 до 9 по обоим измерениям

**Comment by siromanto** [comment]
Whiteq, извини, но я закрыл этот таск. Просто все следующие задания зависят от этого. Если хочешь, то возьми мой.

**Comment by Whiteq** [comment]
Привет. Без проблем) У меня в пятницу не вышло прийти на занятие и все
выходные бил занят, поэтому все нормально)

7 декабря 2015 г., 11:05 пользователь serhiidmytrenko <
notifications@github.com> написал:
