### ISSUE TITLE
Выстрел

### ISSUE THREAD

**Issue by denyszamiatin** [denyszamiatin/sea_battle#5]
Написать функцию, которая получает координаты выстрела и сообщает, есть ли попадание

**Comment by siromanto** [comment]
При створенні тесту в gedit функція player_shoot(coord) працює і при попаданні друкує "You hit a ship!" при промасі -  "You missed!"
В доктестах завжди видає 
Expected:
    You hit a ship!
Got:
    You missed!
[sea_battle_shoot.py.txt](https://github.com/denyszamiatin/sea_battle/files/60603/sea_battle_shoot.py.txt)
